#!/usr/bin/env python3
# -*- encoding: utf-8 -*-

""" picks

"""
import os

from contextlib import suppress
from application import main

if __name__ == "__main__":
    with suppress(KeyboardInterrupt, BrokenPipeError):
        raise SystemExit(main())
